version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - payment-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "payment-topic:1:1"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

    networks:
      - payment-network
    depends_on:
      - zookeeper


  dbservice:
    image: postgres
    container_name: postgres-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    networks:
      - payment-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      - dbservice
      - zookeeper
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbservice:5432/productdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      SPRING_KAFKA_BROKER-LIST: kafka:9092
      SPRING_KAKFA_CONSUMER_GROUP-ID: product-service
    ports:
      - "8081:8081"
    networks:
      - payment-network


  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8082:8082"
    networks:
      - payment-network
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      SPRING_KAFKA_BROKER-LIST: kafka:9092
      SPRING_KAKFA_CONSUMER_GROUP-ID: product-service
      SPRING_KAKFA_CONSUMER_AUTO-OFFSET-RESET: earliest
    depends_on:
      - product-service
      - zookeeper
      - kafka

networks:
  payment-network:
    driver: bridge

volumes:
  postgres-data: